#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory


# Source clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

# Clean time directories and ./constant/polyMesh
cleanCase

# Clean plots directory
rm -rf logs > /dev/null 2>&1

# ----------------------------------------------------------------- end-of-file


