#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
set -x

wclean libso subChannelMesh
wclean libso GeometricRodField
wclean libso Core
wclean

# ----------------------------------------------------------------- end-of-file


